<a href="https://colab.research.google.com/github/srishanthdevoju/IPLAuctionManagementSystem/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("HI")

HI


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr2=np.array([[1,2],[4,6]])
print(arr2.ndim)
arr3=np.array([[[1,2],[2,5]], [[9,3],[4,6]]])
print(arr3)
print(arr3)
randomarr= np.random.random((2,2))
print(randomarr)
onesarr=np.ones((1,4))
print(onesarr)

[1 2 3 4 5]
2
[[[1 2]
  [2 5]]

 [[9 3]
  [4 6]]]
[[[1 2]
  [2 5]]

 [[9 3]
  [4 6]]]
[[0.6476099  0.14397365]
 [0.33752132 0.93738153]]
[[1. 1. 1. 1.]]


In [ ]:
import numpy as np
arangearr=np.arange(1,7,4)
print(arangearr)

[1 5]


In [ ]:
dtype1=arr.dtype
dtype2=arr3.dtype
print(dtype1)
print(dtype2)
shape=arr.shape
print(shape)

int64
int64
(5,)


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [ ]:
gh1=np.array([22,25,20])
gh2=np.array([24,26,23])
temp_data=np.array([gh1,gh2])
print(temp_data)
shape=np.shape(temp_data)
print(shape)
size=np.size(temp_data)
print(size)
print(temp_data.dtype)
print(temp_data.ndim)
gh3=np.array([21, 23, 22])
updated_temp_data=np.array([gh1, gh2, gh3])
print(updated_temp_data)
sensor_error_flags = np.zeros((2, 3), dtype=int)
print(sensor_error_flags)
greenhouse_identity = np.identity(3, dtype=int)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]
(2, 3)
6
int64
2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(arr[2])
print(arr2[1:])
print(arr2[1,1])
print(arr3[0,1,1])
print(arr3[::-1])

3
[[4 6]]
6
5
[[[9 3]
  [4 6]]

 [[1 2]
  [2 5]]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],
                   [40,45,50,60,55,70,75]])
appwed=shipments[0,2]
print(appwed)
ora=sun=shipments[1,-1]
print(ora)
print(shipments[:,0:5])
print(shipments[:,5:])
print(shipments[0,2:6])
shipments[0,5]=100
print(shipments)


55
75
[[50 60 55 70 65]
 [40 45 50 60 55]]
[[80 90]
 [70 75]]
[55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
a=np.array([1,2,3])
b=np.array([9,8,7])
print(a+b)
print(a-b)
print(a*2)
print(a*b)


[10 10 10]
[-8 -6 -4]
[2 4 6]
[ 9 16 21]


In [ ]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[2,3],[2,4]])
res=np.dot(mat1,mat2)
print(res)

[[ 6 11]
 [14 25]]


In [ ]:
m1=np.array([1,2,3])
b=2
print(m1+b)

[3 4 5]


In [ ]:
print(np.exp(m1))

[ 2.71828183  7.3890561  20.08553692]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [ ]:
print(np.lcm(10,20))
print(np.gcd(10,20))
print(np.invert(10))

20
10
-11


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [ ]:
import numpy as np
farmA = np.array([
    [10, 12, 11],
    [9, 11, 10],
    [12, 13, 14],
    [8, 7, 9]
])

farmB = np.array([
    [20, 19, 21],
    [18, 20, 19],
    [22, 23, 21],
    [17, 18, 16]
])

farmC = np.array([
    [15, 16, 14],
    [14, 13, 15],
    [16, 17, 18],
    [12, 11, 13]
])

# -----------------------
# Step 2: Stack into 3D array (3 farms × 4 panels × 3 hours)
production_all = np.array([farmA, farmB, farmC], dtype=float)  # Convert to float for future operations

# Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Dimensions:", production_all.ndim)

# -----------------------
# Step 3: Per-farm totals
total_per_farm = production_all.sum(axis=(1,2))
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
var_per_farm = production_all.var(axis=(1,2))

print("\nTotal energy per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# -----------------------
# Step 4: Weighted per panel
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.tensordot(production_all, hour_weights, axes=([2],[0]))
print("\nWeighted per panel (shape 3x4):\n", weighted_per_panel)

# -----------------------
# Step 5: Broadcast calibration offset (+0.5) to Farm B (index 1)
production_all[1] += 0.5
print("\nFarm B after calibration offset:\n", production_all[1])

# -----------------------
# Step 6: Z-score normalization per farm
normalized = (production_all - mean_per_farm[:,None,None]) / std_per_farm[:,None,None]
print("\nNormalized data (first farm, first row):", normalized[0,0])

# -----------------------
# Step 7: Element-wise ufuncs

# Exponential and log
exp_norm = np.exp(normalized)
expm1_norm = np.expm1(normalized)
log_norm = np.log(normalized - normalized.min() + 1e-5)
log10_norm = np.log10(normalized - normalized.min() + 1e-5)
log2_norm = np.log2(normalized - normalized.min() + 1e-5)

# Trigonometric
sin_norm = np.sin(normalized)
cos_norm = np.cos(normalized)
tan_norm = np.tan(normalized)
arcsin_norm = np.arcsin(np.clip(normalized, -1, 1))
arccos_norm = np.arccos(np.clip(normalized, -1, 1))
arctan_norm = np.arctan(normalized)
degrees_norm = np.degrees(normalized)
radians_norm = np.radians(normalized)

# Rounding
round_norm = np.round(normalized, 2)
floor_norm = np.floor(normalized)
ceil_norm = np.ceil(normalized)
trunc_norm = np.trunc(normalized)

# Logical & comparison
high_output = production_all > 20
even_hours_mask = np.array([True, False, True])
even_hours_mask_exp = even_hours_mask[None,None,:]
logical_and_mask = np.logical_and(high_output, even_hours_mask_exp)
logical_or_mask = np.logical_or(high_output, even_hours_mask_exp)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask_exp)

# Bitwise (example alerts)
alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
bitwise_and = np.bitwise_and(alerts, alerts)
bitwise_or = np.bitwise_or(alerts, alerts)
bitwise_invert = np.bitwise_not(alerts)

# Arithmetic
add_arr = np.add(production_all, 1)
sub_arr = np.subtract(production_all, 1)
mul_arr = np.multiply(production_all, 2)
div_arr = np.divide(production_all, 2)
power_arr = np.power(production_all, 2)
mod_arr = np.mod(production_all, 2)

# Aggregation over ufuncs
sum_exp = np.sum(np.exp(production_all))
mean_sin = np.mean(np.sin(production_all))

# -----------------------
# Step 8: Panel totals & maintenance check
panel_totals_per_farm = production_all.sum(axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Farms needing maintenance:", needs_maintenance)

# -----------------------
# Step 9: Final KPIs
overall_total = production_all.sum()
peak_hour_value = production_all.max()
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
peak_farm, peak_panel, peak_hour = peak_index
average_per_panel = production_all.mean(axis=2)

print("\nOverall total energy:", overall_total)
print("Peak hour value:", peak_hour_value)
print("Produced by Farm", peak_farm, "Panel", peak_panel, "Hour", peak_hour)
print("Average per panel:\n", average_per_panel)


Shape: (3, 4, 3)
Size: 36
Dtype: float64
Dimensions: 3

Total energy per farm: [126. 234. 174.]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Var per farm: [3.91666667 3.91666667 3.91666667]

Weighted per panel (shape 3x4):
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

Farm B after calibration offset:
 [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]

Normalized data (first farm, first row): [-0.25264558  0.75793673  0.25264558]

Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Farms needing maintenance: [ True False  True]

Overall total energy: 540.0
Peak hour value: 23.5
Produced by Farm 1 Panel 2 Hour 1
Average per panel:
 [[11.  10.  13.   8. ]
 [20.5 19.5 22.5 17.5]
 [15.  14.  17.  12. ]]


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3,1))
print(a[a>3])
i=[0,3]
print(a[i])
cp=a.copy()
v=a.view()
a[4]=7
print(cp)
print(v)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[4 5 6]
[1 4]
[1 2 3 4 5 6]
[1 2 3 4 7 6]
[1 2 3 4 5]


In [ ]:
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3 4 5]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [ ]:
nums=np.arange(10,51)
print(nums)
arr=np.random.rand(3,3)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
nums=nums+5
print(nums)
m1=np.array([[1,2],[3,4]])
m2=np.array([[2,4],[1,2]])
print(m1*m2)
arr=np.arange(1,26).reshape(5,5)
print(arr)
first=arr[0,:]
print(first)
last=arr[:,-1]
print(last)
sub1=arr[:3,:2]
print(sub1)
randomnum=np.random.randint(10,101,10)
print(max(randomnum))
print(min(randomnum))
mean=np.mean(randomnum)
print(mean)
stddev=np.std(randomnum)
print(stddev)
new=np.arange(1,13)
res=new.reshape(4,3)
print(res)
ones=np.ones((3,3))
print(ones)
new_add=ones+np.array([1,2,3])
print(new_add)
random=np.random.randint(1,51,50)
div=random[random%5==0]
print(div)
print(m1.dot(m2))
f=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(f.diagonal())

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.06236965 0.10457298 0.22314334]
 [0.23029921 0.76098581 0.56825076]
 [0.28738325 0.5592517  0.06557431]]
(3, 3)
9
float64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[2 8]
 [3 8]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
94
10
55.2
28.7986110776197
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[35 15 50 40 20 25  5 40]
[[ 4  8]
 [10 20]]
[ 1  6 11 16]
